-- ==========================================================================
-- Seed: Abroad Jobs (11 jobs from original abroadJobs array)
-- ==========================================================================
INSERT INTO abroad_jobs (title, company, logo, country, location, type, salary, experience, category, description, apply_url, skills, badge) VALUES
  ('Cabin Crew', 'Emirates', 'EK', 'UAE', 'Dubai, UAE', 'Full Time', '$2,800-3,500/mo', 'Fresher', 'Aviation', 'Join our world-class cabin crew team in Dubai. Accommodation, meals, and travel benefits included. Indian passport holders preferred.', 'https://www.emiratesgroupcareers.com/', ARRAY['Communication','Customer Service','Safety Procedures','Multilingual'], 'New'),
  ('Petroleum Engineer', 'Saudi Aramco', 'SA', 'Saudi Arabia', 'Dhahran, Saudi Arabia', 'Full Time', '$8,000-15,000/mo', '5-10 Yrs', 'Engineering', 'Saudi Aramco hiring Petroleum Engineers for exploration and production projects. Tax-free salary + housing.', 'https://www.aramcojobs.com/', ARRAY['Petroleum Engineering','Reservoir Simulation','Drilling','AutoCAD'], 'Hot'),
  ('Frontend Developer', 'Wipro', 'WI', 'USA', 'New York / Remote', 'Full Time', '$85,000-110,000/yr', '3-6 Yrs', 'IT / Software', 'Wipro USA hiring Frontend Developers for Fortune 500 client projects. H1B sponsorship available.', 'https://careers.wipro.com/', ARRAY['React','TypeScript','Node.js','AWS'], 'New'),
  ('Civil Engineer', 'L&T Construction', 'LT', 'UK', 'London, UK', 'Full Time', '£45,000-60,000/yr', '4-8 Yrs', 'Engineering', 'L&T UK infrastructure projects. Skilled Worker Visa sponsorship available for Indian engineers.', 'https://www.lntecc.com/careers/', ARRAY['Civil Engineering','AutoCAD','Project Management','BIM'], 'New'),
  ('Nurse (ICU)', 'NHS UK', 'NH', 'UK', 'London / Manchester / Birmingham', 'Full Time', '£32,000-45,000/yr', '2+ Yrs', 'Healthcare', 'NHS UK urgently hiring ICU Registered Nurses. Skilled Worker Visa sponsorship. IELTS 7.0+ required.', 'https://www.jobs.nhs.uk/', ARRAY['ICU Care','Patient Management','IELTS','NMC Registration'], 'Hot'),
  ('Software Engineer', 'Google', 'GGL', 'USA', 'New York / London / Singapore', 'Full Time', '$120,000-200,000/yr', '3-6 Yrs', 'IT / Software', 'Google hiring Software Engineers globally. Work on products used by billions. Strong DSA required.', 'https://careers.google.com/', ARRAY['Java','Python','System Design','Distributed Systems'], 'Hot'),
  ('Data Scientist', 'Microsoft', 'MSF', 'USA', 'Seattle / London / Hyderabad', 'Full Time', '$95,000-160,000/yr', '2-5 Yrs', 'Data / Analytics', 'Microsoft Azure AI team hiring Data Scientists. ML model development and cloud deployment.', 'https://careers.microsoft.com/', ARRAY['Python','Machine Learning','Azure ML','SQL'], 'New'),
  ('Registered Nurse ICU', 'NHS Scotland', 'NS', 'UK', 'Edinburgh, Scotland', 'Full Time', '£35,000-45,000/yr', '2+ Yrs', 'Healthcare', 'NHS Scotland urgently hiring ICU Registered Nurses. Visa sponsorship available for Indian nurses. IELTS required.', 'https://www.jobs.nhs.uk/', ARRAY['ICU Care','Clinical Skills','IELTS','NMC'], 'New'),
  ('Civil Engineer', 'AECOM', 'AEC', 'UAE', 'Dubai / Abu Dhabi, UAE', 'Full Time', 'AED 15,000-25,000/mo', '3-7 Yrs', 'Engineering', 'AECOM hiring Civil Engineers for infrastructure megaprojects in UAE. PMP preferred.', 'https://aecom.jobs/', ARRAY['Civil Engineering','BIM','Project Management','AutoCAD'], 'New'),
  ('Accountant (CA/CPA)', 'Deloitte Canada', 'DLT', 'Canada', 'Toronto / Vancouver, Canada', 'Full Time', 'CAD 60,000-90,000/yr', '2-4 Yrs', 'Finance / Accounts', 'Deloitte Canada hiring CA/CPA qualified accountants. PR pathway available for skilled workers.', 'https://www2.deloitte.com/ca/en/careers.html', ARRAY['CA/CPA','Taxation','Financial Reporting','IFRS'], 'New'),
  ('HR Manager', 'Marriott Hotels', 'MRT', 'UAE', 'Dubai / Qatar / Bahrain', 'Full Time', '$3,500-5,500/mo', '4-8 Yrs', 'HR / Recruitment', 'Marriott International hiring HR Managers across GCC countries. Hospitality experience preferred.', 'https://jobs.marriott.com/', ARRAY['HR Management','Recruitment','HRIS','Employment Law'], 'New');
