-- ==========================================================================
-- Seed: India Big Company Curated Jobs (25 entries)
-- Ported from INDIA_BIG_COMPANY_JOBS array in js-live-jobs script
-- ==========================================================================
INSERT INTO jobs (id, employer_id, title, description, location, salary_min, salary_max, currency, job_type, category, skills, experience_required, status, board, source, apply_url, is_verified, badge, posted_at) VALUES
  (gen_random_uuid(), NULL, 'Software Engineer', 'TCS hiring software engineers for digital transformation projects across banking, retail and manufacturing. Training provided.', 'Bangalore / Mumbai / Hyderabad', 600000, 1200000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','Python','Spring Boot','SQL','Git'], '1-3 Years', 'active', 'private', 'TCS — Official Career Page', 'https://ibegin.tcs.com/iBegin/', true, 'Verified', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), NULL, 'Systems Engineer', 'Infosys hiring fresh graduates for systems engineering. Training at Mysore campus. Competitive salary and benefits.', 'Bangalore / Pune / Chennai', 350000, 700000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','C++','DBMS','OS','Networking'], 'Fresher', 'active', 'private', 'Infosys — InfyTQ / Official Portal', 'https://career.infosys.com/', true, 'Verified', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), NULL, 'Project Engineer', 'Wipro hiring project engineers for client-facing IT services. WILP program available for freshers.', 'Bangalore / Hyderabad / Chennai', 400000, 800000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','Python','Testing','Agile','Communication'], 'Fresher / 0-2 Yrs', 'active', 'private', 'Wipro — Careers Portal', 'https://careers.wipro.com/', true, 'Verified', NOW() - INTERVAL '3 days'),
  (gen_random_uuid(), NULL, 'Software Developer', 'HCL Technologies hiring developers for global IT projects. HCL Star program for freshers.', 'Noida / Chennai / Hyderabad', 350000, 750000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','.NET','Angular','SQL'], 'Fresher / 0-2 Yrs', 'active', 'private', 'HCL Technologies', 'https://www.hcltech.com/careers', true, 'Verified', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), NULL, 'Associate Software Engineer', 'Accenture hiring ASEs for digital services. 5-day work week and work from home options.', 'Bangalore / Hyderabad / Pune', 400000, 700000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','Python','Cloud','Communication'], 'Fresher', 'active', 'private', 'Accenture — Careers', 'https://www.accenture.com/in-en/careers', true, 'Hot', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), NULL, 'Programmer Analyst', 'Cognizant hiring programmer analysts for US-based client projects. CTS campus drive and off-campus recruitment.', 'Chennai / Bangalore / Hyderabad', 350000, 700000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','SQL','Testing','Communication'], 'Fresher / 0-2 Yrs', 'active', 'private', 'Cognizant Technology Solutions', 'https://careers.cognizant.com/', true, 'Verified', NOW() - INTERVAL '4 days'),
  (gen_random_uuid(), NULL, 'Operations Manager', 'Amazon India hiring operations managers for fulfilment centres and delivery networks. Strong growth path.', 'Bangalore / Delhi / Mumbai', 1000000, 1800000, 'INR', 'Full Time', 'Operations', ARRAY['Operations','Supply Chain','Leadership','Excel','Process Improvement'], '2-5 Years', 'active', 'private', 'Amazon India — Jobs', 'https://www.amazon.jobs/en/', true, 'Hot', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), NULL, 'Software Development Engineer', 'Amazon India SDE-1/SDE-2 positions for product and platform teams. Competitive equity package.', 'Bangalore / Hyderabad', 1500000, 4500000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','Python','System Design','DSA','AWS'], '2-6 Years', 'active', 'private', 'Amazon India — Engineering', 'https://www.amazon.jobs/en/', true, 'Hot', NOW() - INTERVAL '6 hours'),
  (gen_random_uuid(), NULL, 'Business Technology Analyst', 'Deloitte India hiring BTAs for technology consulting engagements. CA/MBA/Engineering backgrounds.', 'Mumbai / Hyderabad / Bangalore', 800000, 1400000, 'INR', 'Full Time', 'Consulting', ARRAY['SAP','Salesforce','Data Analytics','PowerBI','Communication'], '0-2 Years', 'active', 'private', 'Deloitte India', 'https://www2.deloitte.com/in/en/careers.html', true, 'New', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), NULL, 'Product Manager', 'Flipkart hiring PMs for commerce, logistics and fintech verticals. 3-5 years product experience required.', 'Bangalore', 3000000, 8000000, 'INR', 'Full Time', 'Product Management', ARRAY['Product Strategy','SQL','Analytics','Wireframing','Stakeholder Management'], '3-6 Years', 'active', 'private', 'Flipkart Careers', 'https://www.flipkartcareers.com/', true, 'Hot', NOW() - INTERVAL '3 days'),
  (gen_random_uuid(), NULL, 'Relationship Manager — Retail', 'HDFC Bank hiring RMs for retail banking. Branch and field sales roles across India.', 'Pan India (Multiple Locations)', 400000, 900000, 'INR', 'Full Time', 'Banking / Finance', ARRAY['Sales','Customer Relationship','Banking Products','Communication'], '1-4 Years', 'active', 'private', 'HDFC Bank Careers', 'https://www.hdfcbank.com/careers', true, 'New', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), NULL, 'Member Technical Staff', 'Zoho Corporation hiring MTSs for product engineering roles. India-based team building global SaaS products.', 'Chennai / Coimbatore', 600000, 1400000, 'INR', 'Full Time', 'IT / Software', ARRAY['Java','C++','Python','DSA','Problem Solving'], '1-4 Years', 'active', 'private', 'Zoho Careers', 'https://www.zoho.com/careers.html', true, 'Verified', NOW() - INTERVAL '5 days'),
  (gen_random_uuid(), NULL, 'Graduate Engineer Trainee', 'Tata Motors recruiting GETs for automobile manufacturing and R&D. Pune and Jamshedpur locations.', 'Pune / Jamshedpur', 350000, 600000, 'INR', 'Full Time', 'Engineering', ARRAY['Mechanical Engineering','AutoCAD','Manufacturing','Quality Control'], 'Fresher', 'active', 'private', 'Tata Motors Careers', 'https://www.tatamotors.com/careers/', true, 'New', NOW() - INTERVAL '3 days'),
  (gen_random_uuid(), NULL, 'Junior Engineer (Automobile)', 'Mahindra & Mahindra hiring JEs for SUV and tractor division. Nashik and Pune plants.', 'Nashik / Pune', 350000, 600000, 'INR', 'Full Time', 'Engineering', ARRAY['Mechanical','Production','Quality','AutoCAD'], 'Fresher / 0-2 Yrs', 'active', 'private', 'Mahindra Careers', 'https://careers.mahindra.com/', true, 'New', NOW() - INTERVAL '4 days'),
  (gen_random_uuid(), NULL, 'Civil Engineer (Infrastructure)', 'L&T Construction hiring civil engineers for large-scale infrastructure megaprojects across India and abroad.', 'Mumbai / Delhi / Abroad', 600000, 1500000, 'INR', 'Full Time', 'Engineering', ARRAY['Civil Engineering','AutoCAD','Project Management','BIM','MS Project'], '2-6 Years', 'active', 'private', 'L&T Careers', 'https://www.lntecc.com/careers/', true, 'Verified', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), NULL, 'Store Manager (Retail)', 'Reliance Retail / JioMart hiring store managers for fashion and grocery retail outlets nationwide.', 'Pan India', 400000, 900000, 'INR', 'Full Time', 'Retail / Sales', ARRAY['Retail Operations','Team Management','P&L','Customer Service'], '2-5 Years', 'active', 'private', 'Reliance Retail Careers', 'https://www.relianceretail.com/careers.html', true, 'Hot', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), NULL, 'City Operations Manager', 'Zomato hiring city ops managers for food delivery network expansion in Tier 2/3 cities across India.', 'Multiple Cities (Tier 2/3)', 800000, 1500000, 'INR', 'Full Time', 'Operations', ARRAY['Operations','Logistics','Data Analysis','Leadership','Communication'], '2-4 Years', 'active', 'private', 'Zomato Careers', 'https://www.zomato.com/careers', true, 'Hot', NOW() - INTERVAL '6 hours'),
  (gen_random_uuid(), NULL, 'Delivery Partner', 'Amazon Flex delivery partner program. Earn ₹18,000-25,000/month. Use your own bike/scooter. Flexible hours.', 'Pan India (800+ cities)', 216000, 300000, 'INR', 'Part Time', 'Logistics / Delivery', ARRAY['Driving License','Android Smartphone','Physical Fitness'], 'Fresher', 'active', 'private', 'Amazon Flex India', 'https://flex.amazon.in/', true, 'New', NOW()),
  (gen_random_uuid(), NULL, 'Delivery Executive', 'Swiggy hiring delivery executives for food and grocery delivery. Earn ₹15,000-22,000/month + incentives.', 'Pan India', 180000, 264000, 'INR', 'Full Time', 'Logistics / Delivery', ARRAY['Driving License','Two-Wheeler','Smartphone','Time Management'], 'Fresher', 'active', 'private', 'Swiggy Careers', 'https://careers.swiggy.com/', true, 'New', NOW() - INTERVAL '2 hours'),
  (gen_random_uuid(), NULL, 'Data Entry Operator', 'TCS BPS (Business Process Services) hiring DEOs for back-office operations in banking and insurance.', 'Chennai / Pune / Delhi', 200000, 350000, 'INR', 'Full Time', 'Operations', ARRAY['Typing Speed 35 WPM','MS Excel','Data Entry','Accuracy'], 'Fresher / 12th Pass', 'active', 'private', 'TCS BPS Careers', 'https://ibegin.tcs.com/iBegin/', true, 'New', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), NULL, 'Customer Service Executive', 'HDFC Bank phone banking & credit card customer service. Day shift. Freshers with good communication welcome.', 'Mumbai / Pune / Bangalore', 200000, 350000, 'INR', 'Full Time', 'Customer Support', ARRAY['Communication','Banking','CRM','Hindi','English'], 'Fresher', 'active', 'private', 'HDFC Bank Careers', 'https://www.hdfcbank.com/careers', true, 'New', NOW() - INTERVAL '3 days'),
  (gen_random_uuid(), NULL, 'Senior Software Engineer', 'GitHub is hiring senior software engineers to build the tools that millions of developers use every day. Remote India.', 'Remote — India', 8000000, 15000000, 'INR', 'Remote', 'IT / Software', ARRAY['Ruby','Go','React','Systems Programming','Open Source'], '5-8 Years', 'active', 'private', 'GitHub Jobs', 'https://github.com/about/careers', true, 'Hot', NOW() - INTERVAL '1 day'),
  (gen_random_uuid(), NULL, 'Backend Engineer (Ruby/Go)', 'GitLab all-remote company. Backend engineer for DevOps platform. Equity + competitive pay.', 'Remote — Worldwide (India eligible)', 6000000, 11000000, 'INR', 'Remote', 'DevOps / Cloud', ARRAY['Ruby on Rails','Go','PostgreSQL','Redis','Kubernetes'], '3-7 Years', 'active', 'private', 'GitLab Jobs', 'https://about.gitlab.com/jobs/', true, 'Hot', NOW() - INTERVAL '2 days'),
  (gen_random_uuid(), NULL, 'Senior Frontend Developer', 'Shopify hiring remote senior frontend developers for commerce platform. React + TypeScript stack.', 'Remote — India / Canada', 7000000, 12000000, 'INR', 'Remote', 'IT / Software', ARRAY['React','TypeScript','GraphQL','Accessibility','Performance'], '4-7 Years', 'active', 'private', 'Shopify Careers', 'https://www.shopify.com/careers', true, 'Hot', NOW() - INTERVAL '3 days'),
  (gen_random_uuid(), NULL, 'Happiness Engineer (WordPress)', 'Automattic (WordPress.com parent) hiring remote support engineers. Write code and help customers worldwide.', 'Remote — Worldwide (India eligible)', 3000000, 6000000, 'INR', 'Remote', 'Customer Support', ARRAY['WordPress','PHP','Communication','Technical Writing','Empathy'], '1-3 Years', 'active', 'private', 'Automattic Careers', 'https://automattic.com/work-with-us/', true, 'New', NOW() - INTERVAL '5 days');
