-- ==========================================================================
-- Seed: WFH Jobs (12 jobs from original WFH_JOBS array)
-- ==========================================================================
INSERT INTO wfh_jobs (title, company, logo, color, type, experience, salary, cat, qualification, skills, badge, badge_type, applicants, description, apply_url) VALUES
  ('React Developer - Remote India', 'TechMahindra', 'TM', '#1847d4', 'Full Time Remote', '2-4 Yrs', '₹8-14 LPA', 'IT / Software', 'B.Tech/MCA', ARRAY['React','Node.js','JavaScript','REST API'], 'Hot', 'hot', 342, 'Work from home opportunity with TechMahindra for experienced React developers. Full remote setup provided.', 'https://careers.techmahindra.com/'),
  ('Content Writer (Remote)', 'Naukri', 'NK', '#e11d48', 'Full Time Remote', 'Fresher / 0-1 Yr', '₹3-5 LPA', 'Content Writing', 'Graduate', ARRAY['Content Writing','SEO','WordPress','MS Word'], 'New', 'new', 189, 'Naukri hiring content writers for their blog and product pages. Work from anywhere in India.', 'https://www.naukri.com/content-writer-jobs'),
  ('Data Entry Specialist', 'Genpact', 'GP', '#7c3aed', 'Full Time Remote', 'Fresher / 12th Pass', '₹2.5-4 LPA', 'Data Entry', '12th Pass / Graduate', ARRAY['MS Excel','Data Entry','Typing Speed 40 WPM','Attention to Detail'], 'New', 'new', 421, 'Genpact offering remote data entry specialist role. Flexible shift options available.', 'https://careers.genpact.com/'),
  ('Digital Marketing Executive', 'Flipkart', 'FK', '#f59e0b', 'Full Time Remote', '1-3 Yrs', '₹5-9 LPA', 'Sales & Marketing', 'Graduate / MBA', ARRAY['Digital Marketing','Google Ads','SEO','Analytics'], 'Hot', 'hot', 267, 'Flipkart hiring Digital Marketing Executives for performance campaigns across categories.', 'https://www.flipkartcareers.com/'),
  ('Academic Expert (Maths/Science)', 'BYJU''S', 'BY', '#1d4ed8', 'Full Time Remote', '1-3 Yrs', '₹4-8 LPA', 'Teaching / Tutoring', 'B.Tech/B.Sc', ARRAY['Mathematics','Physics','Teaching','Communication'], 'New', 'new', 534, 'BYJU''S hiring academic experts for their online learning platform. Work from home in India.', 'https://careers.byjus.com/'),
  ('Process Executive (WFH)', 'Infosys BPM', 'IN', '#0e7490', 'Full Time Remote', 'Fresher', '₹2-3.5 LPA', 'Customer Support', 'Graduate', ARRAY['Communication','MS Office','Customer Service'], 'New', 'new', 876, 'Infosys BPM Process Executive role with complete remote working. Night shift allowance available.', 'https://career.infosys.com/'),
  ('Remote Tax Analyst', 'Deloitte', 'DL', '#1e40af', 'Full Time Remote', '2-5 Yrs', '₹10-18 LPA', 'Finance / Accounts', 'CA/MBA Finance', ARRAY['Taxation','Excel','SAP','Financial Analysis'], 'Hot', 'hot', 145, 'Deloitte Tax team hiring analysts for remote work. Big 4 experience counts toward promotion.', 'https://www2.deloitte.com/in/en/careers/'),
  ('Customer Associate (WFH)', 'Amazon', 'AMZ', '#f97316', 'Full Time Remote', 'Fresher', '₹2.5-4 LPA', 'Customer Support', 'Graduate', ARRAY['Communication','Problem Solving','Computer Skills'], 'New', 'new', 1234, 'Amazon Work From Home Customer Associate. Handle customer queries via chat/email. Rotational shifts.', 'https://www.amazon.jobs/en/'),
  ('Tech Support Engineer (Remote)', 'Wipro', 'WI', '#7c3aed', 'Full Time Remote', '1-3 Yrs', '₹4-7 LPA', 'IT / Software', 'B.Tech/BCA', ARRAY['Technical Support','Networking','Windows Server','ITIL'], 'New', 'new', 298, 'Wipro remote tech support for global clients. Laptop and internet reimbursement provided.', 'https://careers.wipro.com/'),
  ('HR Recruiter (WFH)', 'Quess Corp', 'QC', '#059669', 'Full Time Remote', 'Fresher / 0-2 Yrs', '₹3-5 LPA', 'HR / Recruitment', 'Graduate / MBA HR', ARRAY['Recruitment','LinkedIn Recruiting','Communication','ATS'], 'New', 'new', 167, 'Quess Corp hiring remote HR recruiters for IT and non-IT staffing. Work from home pan-India.', 'https://www.quess.com/careers'),
  ('Graphic Designer (Remote)', 'Zomato', 'ZM', '#ef4444', 'Full Time Remote', '1-3 Yrs', '₹6-11 LPA', 'Design & Creative', 'Graduate / Design Diploma', ARRAY['Adobe Photoshop','Illustrator','Canva','UI Design'], '', '', 134, 'Create visual content for social media, app UI, and marketing campaigns. Fully remote.', 'https://www.zomato.com/careers'),
  ('Medical Transcriptionist', 'Omega Healthcare', 'OH', '#16a34a', 'Full Time Remote', 'Fresher', '₹2-4 LPA', 'Healthcare', 'Graduate', ARRAY['Medical Terminology','Typing','Attention to Detail'], 'New', 'new', 156, 'Transcribe medical dictations and reports for US healthcare clients. Full training provided.', 'https://www.omegahealthcare.com/careers/');
